up: 
	./mvnw spring-boot:run
	
up-env:
	./run.sh

install:
	./mvnw clean install

compile:
	./mvnw clean compile

package:
	./mvnw clean package

compose-up:
	docker compose up --build -d

compose-down:
	docker compose down